## Note mclust only works for cont. vars, canot be used for mixed data etc

## We assume some model for the data (Normally like a normal dist )
## The parameters of the model will change from cluster to cluster so for example the mean parameter would be diff for each cluster
## Because we treat the data as being generated by a mixture of unknown sources this is also called 'mixture modelling'
## Unlike k means mixture modelling will permit each item to have a likelihood of being a member of each group


## mclust
# Assumes the data arises from a number of different normal dist. This is why it only makes sense to use CONt. vars and not categorical etc
# finite mixture modeelling
## Data density for 3 clusters is given in notes
## Stuuf in clustering 2 notes on this
my_iris = iris ## Just using iris dataset as no clue what dataset she used
library(mclust)
model1<- Mclust( my_iris[,1:4] )
summary(model1) # Note log likelihood, number of obs, degrees of freedom, & BIC value (BICs are only good for comparing)
table(model1$classification, my_iris$Species)
plot(model1, what = c("classification"))

plot(model1, what = "BIC")
## Shows the BIC for diff number of clusters


## Post Cluster Analysis
## Whats the quality of your answer?
plot(model1, what = "uncertainty")

uncerPlot(model1$z) ## This works better for other data 
